# Generated by Django 3.2.9 on 2021-11-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tejido',
            name='temperatura',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
