# Generated by Django 3.2.9 on 2021-11-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211125_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tejido',
            name='inflamacion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tejido',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paciente', verbose_name='nombre'),
        ),
    ]
