# Generated by Django 3.2.9 on 2021-11-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211125_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tejido',
            name='inflamacion',
            field=models.FloatField(verbose_name='inflamación'),
        ),
    ]
